"""Seed 4 realistic, complete example runs into the `runs` table, using the
bundled synthetic sample documents (see `sample-data/README.md`).

These are hand-authored (not generated by a live LLM call, to keep this
repo's setup free to run) but are coherent, realistic end-to-end traces of
exactly what the graph produces: extracted fields, validation issues,
reconciliation findings (including the headline duplicate-payment catch),
a human decision, and a final status. They exist so the "Run History /
Example Analyses" page has real, varied content to show a visitor before
they run anything themselves.

Run with:
    python -m scripts.seed_examples

Requires the sample ledger to already be loaded (`scripts/seed_ledger.py`)
so the reconciliation findings below match what the live graph would
actually produce against it.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

from app.db.models import Run
from app.db.session import SessionLocal

# Fixed (not random) ids so re-running this script is genuinely idempotent
# -- e.g. every container start in docker-entrypoint.sh -- instead of
# accumulating a fresh set of duplicate example runs each time.
_CLEAN_MATCH_ID = "seed-inv-1001-clean-match"
_DUPLICATE_ID = "seed-inv-1006-duplicate"
_OVER_THRESHOLD_ID = "seed-inv-2044-over-threshold"
_NO_MATCH_ID = "seed-fm-778-no-match"


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _trace(base: datetime, node: str, minutes: float, summary: str) -> dict:
    return {"node": node, "timestamp": _iso(base + timedelta(minutes=minutes)), "summary": summary}


def _line_item(description: str, quantity: float, unit_price: float, amount: float) -> dict:
    return {"description": description, "quantity": quantity, "unit_price": unit_price, "amount": amount}


def build_clean_match_run() -> Run:
    """INV-1001 Bright Office Supplies -- clean ledger match, approved as-is."""
    run_id = _CLEAN_MATCH_ID
    t0 = datetime.now(timezone.utc) - timedelta(days=4, hours=3)
    line_items = [
        _line_item("Copy Paper, Case of 10 Reams", 5, 42.00, 210.00),
        _line_item("Ergonomic Office Chair", 2, 249.00, 498.00),
        _line_item("Wireless Keyboard & Mouse Combo", 3, 35.00, 105.00),
        _line_item("Toner Cartridge (Black, High Yield)", 4, 89.25, 357.00),
    ]
    extracted = {
        "vendor": "Bright Office Supplies Inc.",
        "document_number": "INV-1001",
        "document_date": "2026-08-05",
        "line_items": line_items,
        "subtotal": 1170.00,
        "tax": 96.53,
        "total": 1266.53,
        "currency": "USD",
    }
    validation_issues: list[dict] = []
    reconciliation_findings = [
        {
            "code": "ledger_match_found",
            "severity": "info",
            "message": "Matched ledger entry #1: Bright Office Supplies Inc., 1266.53 USD on 2026-08-05 (6100-Office Supplies).",
            "details": {"ledger_entry_id": 1, "gl_account": "6100-Office Supplies"},
        }
    ]
    trace = [
        _trace(t0, "ingest", 0.0, "Detected invoice PDF; extracted 612 chars of text."),
        _trace(t0, "extract_fields", 0.4, "Extracted vendor='Bright Office Supplies Inc.', total=1266.53, 4 line item(s)."),
        _trace(t0, "validate", 0.5, "0 validation issue(s) found (severities: none)."),
        _trace(t0, "reconcile", 0.6, "1 finding(s); matched=yes; duplicate=False; requires_approval=False."),
        _trace(t0, "human_review", 25.0, "Human decision=approve | Matches vendor invoice and GL posting exactly."),
        _trace(t0, "finalize", 25.1, "Document finalized with status=posted."),
    ]
    state_snapshot = {
        **extracted,
        "doc_type": "invoice",
        "validation_issues": validation_issues,
        "reconciliation_findings": reconciliation_findings,
        "ledger_match_id": 1,
        "is_duplicate": False,
        "requires_approval": False,
        "human_decision": "approve",
        "human_feedback": "Matches vendor invoice and GL posting exactly.",
        "final_status": "posted",
        "status": "completed",
    }
    return Run(
        id=run_id,
        original_filename="INV-1001_bright_office_supplies.pdf",
        doc_type="invoice",
        status="completed",
        final_status="posted",
        extracted_fields=extracted,
        validation_issues=validation_issues,
        reconciliation_findings=reconciliation_findings,
        trace=trace,
        state_snapshot=state_snapshot,
        error=None,
        created_at=t0,
        updated_at=t0 + timedelta(minutes=25.1),
    )


def build_duplicate_payment_run() -> Run:
    """INV-1006 -- near-duplicate resubmission of INV-1001. This is the
    headline finding: reconcile catches the duplicate payment and the
    accountant rejects it."""
    run_id = _DUPLICATE_ID
    t0 = datetime.now(timezone.utc) - timedelta(days=4, hours=2)
    line_items = [
        _line_item("Copy Paper, Case of 10 Reams", 5, 42.00, 210.00),
        _line_item("Ergonomic Office Chair", 2, 249.00, 498.00),
        _line_item("Wireless Keyboard & Mouse Combo", 3, 35.00, 105.00),
        _line_item("Toner Cartridge (Black, High Yield)", 4, 89.25, 357.00),
    ]
    extracted = {
        "vendor": "Bright Office Supplies Inc.",
        "document_number": "INV-1006",
        "document_date": "2026-08-07",
        "line_items": line_items,
        "subtotal": 1170.00,
        "tax": 96.53,
        "total": 1266.53,
        "currency": "USD",
    }
    validation_issues: list[dict] = []
    reconciliation_findings = [
        {
            "code": "ledger_match_found",
            "severity": "info",
            "message": "Matched ledger entry #2: Bright Office Supplies Inc., 1266.53 USD on 2026-08-07 (6100-Office Supplies).",
            "details": {"ledger_entry_id": 2, "gl_account": "6100-Office Supplies"},
        },
        {
            "code": "duplicate_payment_suspected",
            "severity": "error",
            "message": (
                "Possible duplicate payment: 1 other ledger entry for the same vendor and "
                "amount within 14 days (#1 on 2026-08-05)."
            ),
            "details": {"duplicate_ledger_ids": [1]},
        },
    ]
    trace = [
        _trace(t0, "ingest", 0.0, "Detected invoice PDF; extracted 608 chars of text."),
        _trace(t0, "extract_fields", 0.4, "Extracted vendor='Bright Office Supplies Inc.', total=1266.53, 4 line item(s)."),
        _trace(t0, "validate", 0.5, "0 validation issue(s) found (severities: none)."),
        _trace(t0, "reconcile", 0.6, "2 finding(s); matched=yes; duplicate=True; requires_approval=False."),
        _trace(t0, "human_review", 40.0, "Human decision=reject | This is a duplicate of INV-1001, already paid 2026-08-05. Voiding."),
        _trace(t0, "finalize", 40.1, "Document finalized with status=rejected."),
    ]
    state_snapshot = {
        **extracted,
        "doc_type": "invoice",
        "validation_issues": validation_issues,
        "reconciliation_findings": reconciliation_findings,
        "ledger_match_id": 2,
        "is_duplicate": True,
        "requires_approval": False,
        "human_decision": "reject",
        "human_feedback": "This is a duplicate of INV-1001, already paid 2026-08-05. Voiding.",
        "final_status": "rejected",
        "status": "rejected",
    }
    return Run(
        id=run_id,
        original_filename="INV-1006_bright_office_supplies_DUPLICATE.pdf",
        doc_type="invoice",
        status="rejected",
        final_status="rejected",
        extracted_fields=extracted,
        validation_issues=validation_issues,
        reconciliation_findings=reconciliation_findings,
        trace=trace,
        state_snapshot=state_snapshot,
        error=None,
        created_at=t0,
        updated_at=t0 + timedelta(minutes=40.1),
    )


def build_over_threshold_run() -> Run:
    """INV-2044 Summit Cloud Hosting -- matched, but exceeds the policy
    approval threshold; approved after manager sign-off."""
    run_id = _OVER_THRESHOLD_ID
    t0 = datetime.now(timezone.utc) - timedelta(days=3, hours=5)
    line_items = [
        _line_item("Cloud Compute - Production Cluster (Monthly)", 1, 2400.00, 2400.00),
        _line_item("Object Storage - 5TB Tier", 1, 350.00, 350.00),
        _line_item("Premium Support Plan", 1, 500.00, 500.00),
    ]
    extracted = {
        "vendor": "Summit Cloud Hosting LLC",
        "document_number": "INV-2044",
        "document_date": "2026-08-10",
        "line_items": line_items,
        "subtotal": 3250.00,
        "tax": 268.13,
        "total": 3518.13,
        "currency": "USD",
    }
    validation_issues: list[dict] = []
    reconciliation_findings = [
        {
            "code": "ledger_match_found",
            "severity": "info",
            "message": "Matched ledger entry #3: Summit Cloud Hosting LLC, 3518.13 USD on 2026-08-10 (6400-IT Services).",
            "details": {"ledger_entry_id": 3, "gl_account": "6400-IT Services"},
        },
        {
            "code": "exceeds_policy_threshold",
            "severity": "warning",
            "message": "Total 3518.13 exceeds the $3,000.00 policy threshold and requires additional approval before posting.",
            "details": {"threshold": 3000.0},
        },
    ]
    trace = [
        _trace(t0, "ingest", 0.0, "Detected invoice PDF; extracted 540 chars of text."),
        _trace(t0, "extract_fields", 0.4, "Extracted vendor='Summit Cloud Hosting LLC', total=3518.13, 3 line item(s)."),
        _trace(t0, "validate", 0.5, "0 validation issue(s) found (severities: none)."),
        _trace(t0, "reconcile", 0.6, "2 finding(s); matched=yes; duplicate=False; requires_approval=True."),
        _trace(t0, "human_review", 180.0, "Human decision=approve | Manager sign-off obtained via email 2026-08-11; within budget."),
        _trace(t0, "finalize", 180.1, "Document finalized with status=posted."),
    ]
    state_snapshot = {
        **extracted,
        "doc_type": "invoice",
        "validation_issues": validation_issues,
        "reconciliation_findings": reconciliation_findings,
        "ledger_match_id": 3,
        "is_duplicate": False,
        "requires_approval": True,
        "human_decision": "approve",
        "human_feedback": "Manager sign-off obtained via email 2026-08-11; within budget.",
        "final_status": "posted",
        "status": "completed",
    }
    return Run(
        id=run_id,
        original_filename="INV-2044_summit_cloud_hosting.pdf",
        doc_type="invoice",
        status="completed",
        final_status="posted",
        extracted_fields=extracted,
        validation_issues=validation_issues,
        reconciliation_findings=reconciliation_findings,
        trace=trace,
        state_snapshot=state_snapshot,
        error=None,
        created_at=t0,
        updated_at=t0 + timedelta(minutes=180.1),
    )


def build_no_match_run() -> Run:
    """FM-778 Redwood Facilities Maintenance -- no ledger entry found;
    approved with a note to code it manually."""
    run_id = _NO_MATCH_ID
    t0 = datetime.now(timezone.utc) - timedelta(days=2, hours=1)
    line_items = [
        _line_item("HVAC Quarterly Service", 1, 380.00, 380.00),
        _line_item("Janitorial Supplies Restock", 1, 145.00, 145.00),
        _line_item("Emergency Lock Repair", 1, 87.75, 87.75),
    ]
    extracted = {
        "vendor": "Redwood Facilities Maintenance",
        "document_number": "FM-778",
        "document_date": "2026-08-12",
        "line_items": line_items,
        "subtotal": 612.75,
        "tax": 0.0,
        "total": 612.75,
        "currency": "USD",
    }
    validation_issues: list[dict] = []
    reconciliation_findings = [
        {
            "code": "no_ledger_match",
            "severity": "warning",
            "message": (
                "No ledger entry found matching vendor='Redwood Facilities Maintenance', "
                "amount=612.75, date near 2026-08-12. This document may need to be coded to "
                "the GL manually."
            ),
            "details": {},
        }
    ]
    trace = [
        _trace(t0, "ingest", 0.0, "Detected invoice PDF; extracted 420 chars of text."),
        _trace(t0, "extract_fields", 0.4, "Extracted vendor='Redwood Facilities Maintenance', total=612.75, 3 line item(s)."),
        _trace(t0, "validate", 0.5, "0 validation issue(s) found (severities: none)."),
        _trace(t0, "reconcile", 0.6, "1 finding(s); matched=no; duplicate=False; requires_approval=False."),
        _trace(t0, "human_review", 15.0, "Human decision=approve | Verified via vendor statement; will code to 6200-Facilities manually."),
        _trace(t0, "finalize", 15.1, "Document finalized with status=posted."),
    ]
    state_snapshot = {
        **extracted,
        "doc_type": "invoice",
        "validation_issues": validation_issues,
        "reconciliation_findings": reconciliation_findings,
        "ledger_match_id": None,
        "is_duplicate": False,
        "requires_approval": False,
        "human_decision": "approve",
        "human_feedback": "Verified via vendor statement; will code to 6200-Facilities manually.",
        "final_status": "posted",
        "status": "completed",
    }
    return Run(
        id=run_id,
        original_filename="FM-778_redwood_facilities.pdf",
        doc_type="invoice",
        status="completed",
        final_status="posted",
        extracted_fields=extracted,
        validation_issues=validation_issues,
        reconciliation_findings=reconciliation_findings,
        trace=trace,
        state_snapshot=state_snapshot,
        error=None,
        created_at=t0,
        updated_at=t0 + timedelta(minutes=15.1),
    )


def seed() -> None:
    with SessionLocal() as db:
        for build in (
            build_clean_match_run,
            build_duplicate_payment_run,
            build_over_threshold_run,
            build_no_match_run,
        ):
            run = build()
            existing = db.get(Run, run.id)
            if existing is None:
                db.add(run)
        db.commit()
    print("Seeded 4 example runs.")


if __name__ == "__main__":
    seed()
